backend:
  name: git-gateway
  branch: main

media_folder: "frontend/images/blogs"
public_folder: "/images/blogs"

collections:
  - name: "blogs"
    label: "Blogs"
    folder: "frontend/blogs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
